### ISSUE TITLE
something warning when using the gtf2bed step

### ISSUE THREAD

**Issue by yuanwsy** [yuntianf/Longcell-pre#3]
Hi,

Thanks for developing this very useful and much needed tool!

When using the step1: transform gtf to gene bed,before finished,the command line give a warning:
Warning message:
In .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.

Dose it matter when I using the following step?

**Comment by yuntianf** [comment]
Hi,
It shouldn't matter the downstream step. 
If you want a double check you could share part of the output.
And we notice that LongcellPre is a wrap of bash scripts, which is kind hard to use, currently we have rebuilt it into an R package, and will release it in recent two weeks. I would recommend to use that new version.

Thanks

**Comment by yuanwsy** [comment]
the output contains three type of file ,

the first file  is exon_gtf.rds with five column,the first line looks like:
3143476 | 3144545 | ENSMUSG00000102 | ENSMUST00000193812.2 | ENSMUSE00001343744.2

the second file is gene_bed.rds with six column,the first line looks like:
chr1 | 3143476 | 3144545 | 1070 | + | ENSMUSG00000102

and there is alot of file ,like ENSMUSG00000031.txt ,looks like:
chr1 60382482 60382616 135 +

is it right ?

Looking forward to see the R package qucikly！
Thanks for developing such a good tool!

**Comment by yuanwsy** [comment]
and it seems matter?

when I ran the next step ,it cannot generate useful output,all the output is 0kb
it comes alot error like:

Namespace(bam='/data/R02/yuanwsy/Longcell-pre/OEalignment/OEalignVM34.bam', gene_bed='/data/R02/yuanwsy/Longcell-pre/mousebed/ENSMUSG00000112.txt', out_path='/data/R02/yuanwsy/Longcell-pre/OEisoquantificationVm34//exon_reads/', toolkit='3')
Traceback (most recent call last):
  File "./SoftclipsExon/softclip_splicesite.py", line 166, in <module>
    for samrd in sam_input.fetch(gene_chr,gene_start, gene_end):
  File "pysam/libcalignmentfile.pyx", line 1091, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 688, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid coordinates: start (138382074) > stop (81240539)
cat: /data/R02/yuanwsy/Longcell-pre/OEisoquantificationVm34//exon_reads/EN*: No such file or directory
Extraction of softclips and splice sites finished!
Namespace(barcodes='/data/R02/yuanwsy/Longcell-pre/OEbarcodes.txt.txt', batch=100, cores=16, cos_thresh=0.25, kmer=8, mu=20, output='/data/R02/yuanwsy/Longcell-pre/OEisoquantificationVm34//barcode_match/bc.txt', project='Longcell_bc', seq='/data/R02/yuanwsy/Longcell-pre/OEisoquantificationVm34//softclips/softclips.txt', sigma=10, sigma_start=10, top=8)
tasks will run on 16 cores
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
sh: /data/R02/yuanwsy/Longcell-pre/scripts/BarcodeMatch/BarcodeMatch: Permission denied
Traceback (most recent call last):
  File "./BarcodeMatch/BarcodeMatch.py", line 107, in <module>
    barcode_match(args)
  File "./BarcodeMatch/BarcodeMatch.py", line 98, in barcode_match
    for line in open(filename):
FileNotFoundError: [Errno 2] No such file or directory: 'Longcell_bc_output_sub_0.txt'
Barcode Match finished!

**Comment by yuntianf** [comment]
Hi yuanwsy,
Thanks for the updating from @alihamraoui for the gtf annotation for mouse. You could try it again to see if it could work.
If it still runs into errors, because this version of Longcell-pre would not be maintained, please wait a while for the new package, I will try my best to get it out this week.
Thanks
